import { OrderStatus } from "@/types/order";

export const columnsKanban = [
  {
    key: OrderStatus.PENDING,
    title: "Chờ xác nhận",
    color: "#a1a1aa",
    bgColor: "#27272a",
    badgeBgColor: "#52525b",
    badgeTextColor: "#fafafa",
    description: "Đơn hàng chờ xác nhận (Pending)",
    status: OrderStatus.PENDING,
    canDrag: false,
  },
  {
    key: OrderStatus.CONFIRMED,
    title: "Lên đơn",
    color: "#69b1ff",
    bgColor: "#1e3a5f",
    badgeBgColor: "#1677ff",
    badgeTextColor: "#fafafa",
    description: "Đơn hàng đã xác nhận (Confirmed)",
    status: OrderStatus.CONFIRMED,
  },
  {
    key: OrderStatus.IN_PROGRESS,
    title: "Sản xuất",
    color: "#fadb14",
    bgColor: "#3f3f46",
    badgeBgColor: "#fadb14",
    badgeTextColor: "#18181b",
    description: "Đang thực hiện (In Progress)",
    status: OrderStatus.IN_PROGRESS,
  },
  {
    key: OrderStatus.ON_HOLD,
    title: "Thanh toán",
    color: "#b37feb",
    bgColor: "#3d2a4f",
    badgeBgColor: "#722ed1",
    badgeTextColor: "#fafafa",
    description: "Chờ thanh toán (On Hold)",
    status: OrderStatus.ON_HOLD,
  },
  {
    key: OrderStatus.COMPLETED,
    title: "CSKH",
    color: "#73d13d",
    bgColor: "#2d4a2d",
    badgeBgColor: "#52c41a",
    badgeTextColor: "#fafafa",
    description: "Chăm sóc khách hàng (Completed)",
    status: OrderStatus.COMPLETED,
  },
];
